function (add_arduino_board board_name)
    message(STATUS "Adding Board: ${board_name}...")
    if (board_name STREQUAL "Arduino UNO")
        set(ARDUINO_BOARD "AVR_UNO" PARENT_SCOPE)
        set(ARDUINO_MCU "atmega328p" PARENT_SCOPE)
        set(ARDUINO_F_CPU "16000000L" PARENT_SCOPE)
        set(ARDUINO_VERSION "1.8.6" PARENT_SCOPE)
        set(ARDUINO_FIRMWARE_MAX_SIZE "30720" PARENT_SCOPE)
        set(ARDUINO_USB Off PARENT_SCOPE)
        set(ARDUINO_VARIANT "standard" PARENT_SCOPE)
    elseif(board_name STREQUAL "Arduino Nano")
        message(VERBOSE "Adding board Arduino Nano")
        set(ARDUINO_BOARD "AVR_NANO" PARENT_SCOPE)
        set(ARDUINO_MCU "atmega328p" PARENT_SCOPE)
        set(ARDUINO_F_CPU "16000000L" PARENT_SCOPE)
        set(ARDUINO_VERSION "1.8.6" PARENT_SCOPE)
        set(ARDUINO_FIRMWARE_MAX_SIZE "30720" PARENT_SCOPE)
        set(ARDUINO_USB Off PARENT_SCOPE)
        set(ARDUINO_VARIANT "standard" PARENT_SCOPE)
    elseif(board_name STREQUAL "Mega 2560")
        set(ARDUINO_BOARD "AVR_MEGA2560" PARENT_SCOPE)
        set(ARDUINO_MCU "atmega2560" PARENT_SCOPE)
        set(ARDUINO_F_CPU "16000000L" PARENT_SCOPE)
        set(ARDUINO_VERSION "1.8.6" PARENT_SCOPE)
        set(ARDUINO_FIRMWARE_MAX_SIZE "253952" PARENT_SCOPE)
        set(ARDUINO_USB Off PARENT_SCOPE)
        set(ARDUINO_VARIANT "mega" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Board: ${board_name} is not found or not supported")
    endif()
    message(STATUS "Successfully Added Board: ${board_name}")
endfunction()